syntax = "proto2";

option java_package = "io.corrlang.protocol";

service CorrLangService {
  rpc RegisterTechSpace (RegisterTechSpaceRequest) returns (TechSpaceRegistered);

  rpc ParseSchema (ParseEndpointSchemaRequest) returns (stream SchemaElement);
  rpc SerializeSchema (stream SchemaElement) returns (BinaryData);

  rpc ParseData (BinaryData) returns (stream TreeData);
  rpc SerializeData (stream TreeData) returns (BinaryData);

}


message BinaryData {
  required int32 byteLength = 1;
  required bytes content = 2;
}

message RegisterTechSpaceRequest {
  required string techSpaceName = 1;
  optional int32 runningOnPort = 2;
  optional string localFileSystemLocation = 3;
  repeated TechSpaceCapabilities capabilities = 4;
}

enum TechSpaceCapabilities {
  PARSE_SCHEMA = 1;
  PARSE_SCHEMA_FROM_URL = 2;
  PARSE_DATA = 3;
  PARSE_DATA_FROM_URL = 4;
  PARSE_COMMAND = 5;
  SERIALIZE_SCHEMA = 6;
  SERIALIZE_DATA = 7;
  SERIALIZE_COMMAND = 8;
}

message TechSpaceRegistered {
  optional string systemServiceHostname = 1;
  optional string systemServicePort = 2;
  optional string systemServiceDataDir = 3;
}

message ParseEndpointSchemaRequest {
  required string techSpaceName = 1;
  oneof location {
    string localFileSystemLocation = 2;
    string urlLocation = 3;
  }
}

enum SchemaElementType {
  OBJECT_TYPE = 1;
  DATA_TYPE = 2;
  ATTRIBUTE = 3;
  REFERENCE = 4;
  ACTION = 5;
  ACTION_INPUT = 6;
  ACTION_OUTPUT = 7;
  ACTION_GROUP = 8;
  ANNOTATION = 9;
}

message SchemaElement {
  repeated string fullyQualifiedName = 1;
  optional string displayName = 2;
  optional string documentationText = 3;
  required SchemaElementType elementType = 4;
  oneof elementDetails {
    ObjectTypeInformation objectTypeDetails = 11;
    DataTypeKinds dataTypeDetails  = 12;
    AttributeTypeInformation attributeTypeDetails = 13;
    ReferenceTypeInformation referenceTypeDetails = 14;
  }
}

message ObjectTypeInformation {
  optional bool isAbstract = 1;
  optional bool isSingleton = 2;
}

enum DataTypeKinds {
  BOOLEAN = 0;
  UNSIGNED_INTEGER = 1;
  SIGNED_INTEGER = 2;
  IEEE754_FLOATING_POINT = 3;
  UTF8_BYTES = 4;
  TIMESTAMP = 5;
  TIME_INTERVAL = 6;
  ARBITRARY_BYTE_SEQUENCE = 7;
}

message DataTypeInformation {
  required DataTypeKinds kind = 1;
  optional uint32 noOfBytes = 2;
  optional string minValue = 3;
  optional string maxValue = 4;
  optional string resolution = 5;
  optional string pattern = 6;
  optional string implementationDetails = 7;
}

message Multiplicity {
  optional uint32 lowerBound = 1;
  optional uint32 upperBound = 2;
}

message AttributeTypeInformation {
  optional Multiplicity multiplicity = 1;
  optional string defaultValue = 2;
}

message ReferenceTypeInformation {
  optional Multiplicity multiplicity = 1;
  optional bool hasInverse = 2;
  optional bool isAcylic = 3;
  optional bool isContainment = 4;
  repeated string inverseName = 5;
  optional Multiplicity inverseMultiplicity = 6;
}

message TreeData {
  oneof treeElementKind {
    BeginRoot beginRoot = 1;
    BeginBranch beginBranch = 2;
    Leaf leaf = 3;
    EndBranch endBranch = 4;
    EndRoot endRoot = 5;
  }
}

message BeginRoot {
  required string rootType = 1;
}

message EndRoot {
}

message BeginBranch {
  required string branchName = 1;
  required string childrenType = 2;
  optional Multiplicity multiplicity = 3;
  optional bool isOrdered = 4;
}

message EndBranch {
  required string branchName = 1;
}

message Leaf {
  required string typeName = 1;
  oneof value {
      StringValue stringValue = 2;
      IntValue intValue = 3;
      FloatValue floatValue = 4;
      BoolValue boolValue = 5;
      CustomValue customValue = 6;
  }
}

message StringValue {
  required string value = 1;
}

message IntValue {
  required int64 value = 1;
}

message FloatValue {
  required double value = 1;
}

message BoolValue {
  required bool value = 1;
}

message CustomValue {
  required BinaryData value = 1;
}


