<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="flowchart" nsURI="http://www.hvl.no/pcs955/mt/flowchart" nsPrefix="flow">
  <eClassifiers xsi:type="ecore:EClass" name="Flowchart">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eAnnotations source="gmf.link">
      <details key="source" value="src"/>
      <details key="target" value="trg"/>
      <details key="target.decoration" value="arrow"/>
      <details key="label" value="lbl"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lbl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="figure" value="ellipse"/>
      <details key="color" value="0,255,0"/>
      <details key="label" value="text"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="label" value="text"/>
      <details key="figure" value="rounded"/>
      <details key="color" value="255,255,255"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="color" value="238,130,238"/>
      <details key="label" value="text"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="color" value="0,100,255"/>
      <details key="label" value="text"/>
      <details key="label.pattern" value="Input: {0}"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="color" value="210,105,30"/>
      <details key="label" value="text"/>
      <details key="label.pattern" value="Output: {0}"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
